package ksiagarnia.com;

/**
 * Enum w formie odpowiedzi w ksiegarni aby latwiej napisac UnitTest
 */
public enum Odpowiedz {
    UZYTKOWNIK_NIE_ISTNIEJE,
    KSIAZKA_NIE_ISTNIEJE,
    SKLEP_KSIAZKA_NIE_JEST_DOSTEPNA,
    WYPOZYCZALNIA_KSIAZKA_NIE_JEST_DOSTEPNA,
    NIGDY_NIE_WYPOZYCZYL_KSIAZKI,
    UZYTKOWNIK_NIE_MA_KASY,
    OK,
    LOGOWANIE_BLAD,
    LOGOWANIE_OK,
    LOGOWANIE_ADMIN_OK,
    ADMIN_LOGIN_POTRZEBNY,
    REJESTRACJA_OK,
    REJESTRACJA_KSIAZKA_NIE_ISTNIEJE
}
